# Volume only container
vol:
  build: ./vol
  restart: always

# strong-pm process manager
# deployment port: 8701
pm:
  image: strongloop/strong-pm
  volumes_from:
    - vol
  ports:
    - "8701:8701"
    - "3000:3000"
    - "3001:3001"
    - "3002:3002"
    - "3003:3003"
  environment:
    - NODE_ENV=production
  links:
    - db
    - mq
    - log
  restart: always

# mongodb
db:
  image: mongo:latest
  volumes_from:
    - vol
  restart: always

# rabbitmq message queue
mq:
  image: rabbitmq:latest
  volumes_from:
    - vol
  restart: always

# splunk logger
# management port: 8000
log:
  image: outcoldman/splunk:latest-light
  volumes_from:
    - vol
  ports:
    - "8000:8000"
  restart: always
